### PR TITLE
add multiconnections

### PR DESCRIPTION
**Pull request by rootedbox**

### CODE REVIEW

**Comment by webelf101** [comment]
Weth addresses are different per chain.

**Review by taariq — APPROVED** [review]
Approved. Waiting for others.

**Review by webelf101 — CHANGES_REQUESTED** [review]
WETH addresses are different per chain. I can provide the addresses but can you update the code so that we can use different WETHs for each chain? @rootedbox

**Comment by rootedbox** [comment]
@webelf101 change made

**Review by webelf101 — CHANGES_REQUESTED** [review]
Thank you. FROM_BLOCK and LOB_CW will be different, too.
And should we use ALTER? Can we modify INSERT directly?
Maybe we can remove the old DB and restart - recreate the DB.

**Pull request merged**
